spring:
  profiles.active: myevent
---
spring:
  profiles: myevent
  kafka:
    bootstrap-servers: "[::1]:9094"
    bootstrap-servers1: "[::1]:9092"
    bootstrap-servers2: "[::1]:9093"
    client-id: first-producer1

demo1:
  kafka:
    bootstrap-servers: "[::1]:9092"
    client-id: clientid1
  topic:
    name: topic1

demo2:
  kafka:
    bootstrap-servers: "[::1]:9094"
    client-id: clientid2
  topic:
    name: topic2

topic:
  name: oltpgwlogevent
