spring:
  profiles.active: myevent
---
spring:
  profiles: myevent
# if we disable spring boot autoconfigure for Kafka, we do not need to set the spring.kafka values any more, instead it will be override in each Consumer Configuration
#  kafka:
#    bootstrap-servers: "[::1]:9092"
#    bootstrap-servers1: "[::1]:9092"
#    bootstrap-servers2: "[::1]:9093"
#    client-id: first-one

demo1:
  kafka:
    bootstrap-servers: "[::1]:9092"
    client-id: clientid1
  topic:
    name: topic1

demo2:
  kafka:
    bootstrap-servers: rulesdeveventhubs.servicebus.windows.net:9093
    client-id: clientid2
    properties:
      sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="$ConnectionString" password="Endpoint=sb://rulesdeveventhubs.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=sR0rb/eAqWT3DPPPJQEnUkzGnaHQdaY/E+vI+cqwA9k=";
      sasl.mechanism: PLAIN
      security.protocol: SASL_SSL
  topic:
    name: oltpgwlogevent


topic:
  name: oltpgwlogevent
